---
- name: Get the OpenStack images
  # TODO: Use the OpenStack collection CLI insteadk of the shell module
  shell: "openstack image list -c ID -c Name -f value | awk '{print $1,$2}'"
  register: image_list

- name: Print the image_list debugging
  debug:
    msg: "{{ image_list }}"

- name: Parse the image list output
  set_fact:
    images: "{{ image_list.stdout_lines | map('split', ' ') | map('list') | list }}"

- name: Print the images debugging
  debug:
    msg: "{{ images }}"

- name: Create the backup directory on the storage server
  ansible.builtin.file:
    path: "/tmp/butca_images}"
    state: directory
    delegate_to: "{{ storage_server_ip }}"
    remote_user: "{{ ssh_user }}"
    ssh_pass: "{{ ssh_password }}"
  when: storage is defined and image_list is defined

# TODO: Edit the images path for the real environment
- name: Copy the images to the storage server
  ansible.builtin.copy:
    src: "/var/lib/glance/images/{{ item[0] }}.img"
    dest: "/tmp/{{ backup_dir_created.stdout }}/{{ item[1] }}.img"
  with_items: "{{ images }}"
  delegate_to: "{{ storage_server_ip }}"
  remote_user: "{{ ssh_user }}"
  ssh_pass: "{{ ssh_password }}"
  when: storage is defined and image_list is defined
