---
- name: Retrieve all available Openstack images
  openstack.cloud.image_info:
  register: glance_images

- name: Create backup directory with timestamp
  command: "mkdir {{ backup_path }}/glance_images/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
  register: backup_dir_created

- name: Fail if backup directory creation failed
  fail:
    msg: "Failed to create backup directory"
  when: backup_dir_created.rc != 0

- name: Download Glance image
  shell: openstack image save --file {{ glance images }}
  executable: /bin/bash

- name: Transfer image to local system
  fetch:
    src: "/tmp/cirros.qcow2"
    dest: "{{ backup_path }}/glance_images/cirros.qcow2"
    flat: yes

# - name: Download Glance images
#   shell:

#     image: "{{ item.id }}"
#     file: "{{ backup_path }}/glance_images/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}/{{ item.name }}"
#   with_items: "{{ glance_images }}"
