---
- name: Retrieve all available Openstack images
  openstack.cloud.image_info:
  register: result

- name: Show images
  debug:
    msg: "{{ result.image }}"

# - name: Create the backup directory on the storage server
#   ansible.builtin.file:
#     path: "/tmp/butca_images"
#     state: directory
#     delegate_to: "{{ storage_server_ip }}"
#     remote_user: "{{ ssh_user }}"
#     ssh_pass: "{{ ssh_password }}"
#   when: storage is defined and image_list is defined

# - name: Copy the images to the storage server
#   ansible.builtin.copy:
#     src: "/var/lib/glance/images/{{ item[0] }}.img"
#     dest: "/tmp/{{ backup_dir_created.stdout }}/{{ item[1] }}.img"
#   with_items: "{{ images }}"
#   delegate_to: "{{ storage_server_ip }}"
#   remote_user: "{{ ssh_user }}"
#   ssh_pass: "{{ ssh_password }}"
#   when: storage is defined and image_list is defined
