---
- name: Check if any database is selected for the restoration
  fail:
    msg: "No database selected for the restoration. Please provide a value for selected_backups in the Variables box."
  when: selected_backups is not defined

- name: Check if selected databases are valid
  fail:
    msg: "Invalid database selected for the restoration: {{ item }}. Please select a valid database from the following list: {{ mariadb_databases }}"
  when: item not in mariadb_databases and item != 'all'
  loop: "{{ selected_backups }}"

- name: Add _dump.sql to selected backups
  set_fact:
    backup_files: "{{ backup_files | default([]) + [item + '_dump.sql'] }}"
  with_items: "{{ mariadb_databases if 'all' in selected_backups else selected_backups }}"

- name: Check if the backup directory exists
  stat:
    path: "{{ backup_dir }}"
  register: backup_dir_status
  failed_when: backup_dir_status.stat.exists == false

- name: Check if the backup files exist in the path
  stat:
    path: "{{ backup_dir }}/{{ item }}"
  loop: "{{ backup_files }}"
  register: backup_files_status
  failed_when: backup_files_status is failed
  changed_when: false
  ignore_errors: true

- name: Fail if any of the backup files are missing
  fail:
    msg: "Backup file {{ item.item }} not found in {{ backup_dir }}"
  loop: "{{ backup_files_status.results }}"
  when: item.stat.exists == false

- name: Check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed
  failed_when: docker_installed.stat.exists == false

- name: Check if MariaDB container is running
  docker_container_info:
    name: mariadb
  register: mariadb_container_info
  failed_when: mariadb_container_info is not defined or
                mariadb_container_info.container.State.Status != "running"

- name: Create the 'backup before restore' directory
  command: "mkdir {{ backup_dir }}/backup_before_restore"
  ignore_errors: true

- name: Start the restore process
  block:
  - name: Restore Cinder database
    include_role:
      name: ../roles/restore_database_roles/cinder
    vars:
      database: cinder
      database_name: cinder_dump.sql
    when: "'cinder' in selected_backups or 'all' in selected_backups"
  
  - name: Restore Glance database
    include_role:
      name: ../roles/restore_database_roles/glance
    vars:
      database: glance
      database_name: glance_dump.sql
    when: "'glance' in selected_backups or 'all' in selected_backups"
  
  - name: Restore Heat database
    include_role:
      name: ../roles/restore_database_roles/heat
    vars:
      database: heat
      database_name: heat_dump.sql
    when: "'heat' in selected_backups or 'all' in selected_backups"
  
  - name: Restore Keystone database
    include_role:
      name: ../roles/restore_database_roles/keystone
    vars:
      database: keystone
      database_name: keystone_dump.sql
    when: "'keystone' in selected_backups or 'all' in selected_backups"

  - name: Restore Neutron database
    include_role:
      name: ../roles/restore_database_roles/neutron
    vars:
      database: neutron
      database_name: neutron_dump.sql
    when: "'neutron' in selected_backups or 'all' in selected_backups"

  - name: Restore Nova database
    include_role:
      name: ../roles/restore_database_roles/nova
    vars:
      database: nova
      database_name: nova_dump.sql
    when: "'nova' in selected_backups or 'all' in selected_backups"

  - name: Restore Nova API database
    include_role:
      name: ../roles/restore_database_roles/nova_api
    vars:
      database: nova_api
      database_name: nova_api_dump.sql
    when: "'nova_api' in selected_backups or 'all' in selected_backups"
  
  - name: Restore Nova Cell0 database
    include_role:
      name: ../roles/restore_database_roles/nova_cell0
    vars:
      database: nova_cell0
      database_name: nova_cell0_dump.sql
    when: "'nova_cell0' in selected_backups or 'all' in selected_backups"

  - name: Restore Placement database
    include_role:
      name: ../roles/restore_database_roles/placement
    vars:
      database: placement
      database_name: placement_dump.sql
    when: "'placement' in selected_backups or 'all' in selected_backups"