- name: Get the hash of the {{ database }}
  stat:
    path: "/tmp/{{ database }}.hash.result"
  register: old_hash

- name: Create temporary new hash file
  file:
    path: "/tmp/{{ database }}.hash.new"
    state: touch

- name: Create new hash of the {{ database }}
  shell: "sha256sum /tmp/{{ database }} | awk '{print $1}'"
  register: new_hash

- name: Save the dump hash to file
  lineinfile:
    line: "{{ new_hash.stdout }}"
    path: "/tmp/{{ database }}.hash.new"

- name: Get the new hash of the {{ database }}
  stat:
    path: "/tmp/{{ database }}.hash.new.result"
  register: new_hash

- name: Fail if the hashes differ
  fail: 
    msg: "The old and the new hash differs, {{ database }} has been probably changed."
  when:  old_hash != new_hash

- name: Delete old hash file
  file:
    path: "/tmp/{{ database }}.hash.new"
    state: absent
  changed_when: false