---
- name: Backup Neutron database
  include_tasks: ../../mariadb/dump_database/tasks/main.yaml
  vars:
    database: neutron
    backup_dir: "{{ backup_path }}/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
