---
- name: Dump the {{ database }} database
  block: 
  - name: Dump the {{ database }} database
    community.docker.docker_container_exec:
      container: mariadb
      command: "mysqldump -u ansible -p{{ mariadb_password }} {{ database }}"
    become: true
    register: dump_output

  - name: Save the dump to the file
    copy:
      content: "{{ dump_output.stdout }}"
      dest: "/tmp/{{ database }}_dump.sql"