- name: Prepare MariaDB for the backup process
  hosts: 10.10.1.11
  become: yes
  vars_files:
    - ../globals.yaml
  tasks:
    - name: Include tasks for backup process
      include_tasks: ../tasks/prepare_backup.yaml