---
- name: Prepare the database for backup
  hosts: 10.10.1.11
  become: yes

  vars_files:
    - ../globals.yaml

  tasks:
    - name: Check if any database is selected for backup
    fail:
      msg: "No database selected for backup. Please provide a value for selected_database in the extra-vars."
    when: selected_database is not defined

    - name: Check if Docker is installed
      become: yes
      stat:
        path: /usr/bin/docker
      register: docker_installed
      failed_when: docker_installed.stat.exists == False

    - name: Check if MariaDB container is running
      become: yes
      docker_container_info:
        name: mariadb
      register: mariadb_container_info
      failed_when: mariadb_container_info is not defined or
                   mariadb_container_info.container.State.Status != "running"
    
    - name: Check if the selected databases exist
      become: true
      community.docker.docker_container_exec:
        container: mariadb
        command: "mysqlshow -u ansible -p{{ mariadb_password }}"
      register: db_check
    
    - name: Set the available databases
      set_fact:
        available_databases: "{{ db_check.stdout_lines | map('split') | map('first') | list }}"
    
    - name: Set the database difference
      set_fact:
        database_difference: "{{ selected_databases | difference(available_databases) }}"
    
    - name: Fail if the selected database(s) do not exist
      fail:
        msg: "Following databases were not found: {{ database_difference }}"
      when: database_difference | length > 0

    - name: Dump selected database(s)
      include_role:
        name: "../roles/{{ item }}"
      with_items: "{{ selected_databases }}"
