---
- name: Backup the BUTCA images to the storage server
  hosts: controller
  vars_files:
    - ../globals.yaml
    
  tasks:
    - name: Authenticate to OpenStack cloud
      shell: source ~/admin-openrc.sh
      args:  
        executable: /bin/bash

    - name: Include tasks for the BUTCA images backup to the storage server
      include_tasks: ../tasks/backup_images.yaml
