- name: Prepare the database for backup
  hosts: 10.10.1.11
  become: yes
   tasks:
    - name: Test MariaDB accessibility
      debug:
        var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    
    - name: Test MariaDB accessibility
      docker_container_info:
        name: mariadb
      register: docker_container_info

    - name: Print container info
      debug:
        var: container_info
    
    - name: Check if container is running
          debug:
            msg: "Container is running"
          when:
            - "'running' in container_info.container.State.Status"
# Add block fail condition
    - name: Dump database
      include_role:
        name: ../roles/keystone