- name: Prepare MariaDB for the backup process
  hosts: 10.10.1.11
  become: yes
  vars_files:
    - ../globals.yaml

  tasks:
    - name: Create backup directory with timestamp
      command: "mkdir /tmp/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
      register: backup_dir_created

    - name: Fail if backup directory creation failed
      fail:
        msg: "Failed to create backup directory"
      when: backup_dir_created.rc != 0

    - name: Check if any database is selected for the backup
      fail:
        msg: "No database selected for backup. Please provide a value for selected_databases in the Variables box."
      when: selected_databases is not defined

    - name: Check if Docker is installed
      become: yes
      stat:
        path: /usr/bin/docker
      register: docker_installed
      failed_when: docker_installed.stat.exists == False

    - name: Check if MariaDB container is running
      become: yes
      docker_container_info:
        name: mariadb
      register: mariadb_container_info
      failed_when: mariadb_container_info is not defined or
                   mariadb_container_info.container.State.Status != "running"
    
    - name: Get a list of available databases
      community.docker.docker_container_exec:
        container: mariadb
        command: "mysql -u ansible -p{{ mariadb_password }} -e 'SHOW DATABASES;'"
      register: db_output

    - name: Extract the list of databases from the output
      set_fact:
        available_databases: "{{ db_output.stdout | split('Database') | last | split('\n') | map('trim') | select | list }}"

    - name: Dump selected database(s)
      include_role:
        name: ../roles/dump_database
      vars:
        database: "{{ item }}"
        backup_dir: "/tmp/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
      with_items: "{{ available_databases if 'all' in selected_databases else selected_databases }}"
      when: item != 'information_schema' and item != 'performance_schema'
