---
- name: Prepare the database for backup
  hosts: 10.10.1.11
  become: yes

  vars_files:
    - ../globals.yaml

  tasks:
    - name: Check if Docker is installed
      become: yes
      stat:
        path: /usr/bin/docker
      register: docker_installed
      failed_when: docker_installed.stat.exists == False

    - name: Check if MariaDB container is running
      become: yes
      docker_container_info:
        name: mariadb
      register: mariadb_container_info
      failed_when: mariadb_container_info is not defined or
                   mariadb_container_info.container.State.Status != "running"
    
    - name: Check if the database exists
      become: true
      community.docker.docker_container_exec:
        container: mariadb
        command: "mysqlshow -u ansible -p{{ mariadb_password }}"
      register: keystone_db_check
    
    # - name: Print the available databases
    #   set_fact:
    #     database_difference: 
    #   when: {{ selected_database }} not in keystone_db_check

    # - name: Fail if the database does not exist
    #   fail:
    #     msg: "Folowing databases were not found {{ database_difference }}"
    #   when:
    #     - keystone_db_check is not defined
    #     - database_difference is defined
                  
    # - name: Dump selected database(s)
    #   include_role:
    #     name: ../roles/{{ selected_database }}