- name: Prepare MariaDB for the backup process
  hosts: controller
  become: yes
  vars_files:
    - ../globals.yaml

  tasks:
    - name: Include tasks for backup process
      include_tasks: ../tasks/prepare_mariadb_backup.yaml
