---
- name: Prepare the database for backup
  hosts: 10.10.1.11
  become: yes

  vars_files:
    - ../globals.yaml

  tasks:
    - name: Check if any database is selected for backup
      fail:
        msg: "No database selected for backup. Please provide a value for selected_database in the Variables box."
      when: selected_databases is not defined

    - name: Check if Docker is installed
      become: yes
      stat:
        path: /usr/bin/docker
      register: docker_installed
      failed_when: docker_installed.stat.exists == False

    - name: Check if MariaDB container is running
      become: yes
      docker_container_info:
        name: mariadb
      register: mariadb_container_info
      failed_when: mariadb_container_info is not defined or
                   mariadb_container_info.container.State.Status != "running"
    
    - name: Get a list of available databases
      community.docker.docker_container_exec:
        container: mariadb
        command: "mysql -u ansible -p{{ mariadb_password }} -e 'SHOW DATABASES;'"
      register: db_output

    - name: Extract the list of databases from the output
      set_fact:
        available_databases: "{{ db_output.stdout | split('\n') }}"

    - name: Dump selected database(s)
      include_role:
        name: "../roles/{{ item }}"
      with_items: "{{ selected_databases }}"
