- name: Prepare the database for backup
  hosts: 10.10.1.11
  become: yes

tasks:
    - name: Check if Docker is installed
      become: yes
      stat:
        path: /usr/bin/docker
      register: docker_installed
      failed_when: docker_installed.stat.exists == False

    - name: Check if MariaDB container is running
      become: yes
      docker_container_info:
        name: mariadb
      register: mariadb_container_info
      failed_when: mariadb_container_info is not defined or
                   mariadb_container_info.State.Status != "running"

    - name: Check if the database exists
      become: yes
      mysql_db:
        login_host: 127.0.0.1
        login_user: ansible
        login_password: "{{ mariadb_password }}"
        name: keystone
      register: keystone_db_check
      failed_when: keystone_db_check is not defined or
                   keystone_db_check.changed == true or
                   keystone_db_check.failed == true

    - name: Dump selected database(s)
      include_role:
        name: ../roles/keystone 