- name: Test MariaDB accessibility
  hosts: controller
  vars_files:
    - roles/test_mariadb/vars/main.yml
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Check if MariaDB is accessible
      mysql_info:
        login_host: "{{ mariadb_host }}"
        login_port: "{{ mariadb_port }}"
        login_user: "{{ mariadb_user }}"
        login_password: "{{ mariadb_password }}"
