- name: Test MariaDB accessibility
  hosts: 10.10.1.11
  become: yes
  vars_files:
    - ../roles/mariadb/vars/mariadb_vars.yaml
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Get container info
      docker_container_info:
        name: mariadb
      register: container_info

    - name: Print container info
      debug:
        var: container_info

    - name: Check if container is running
      debug:
        msg: "Container is running"
      when:
        - "'running' in container_info.container.State.Status"

    - name: Dump database
      community.docker.docker_container_exec:
        container: mariadb
        command: mysqldump -u {{ mariadb_user }} {{ mariadb_database }} > /tmp/{{ mariadb_database }}.sql
      become: yes
      become_user: root
      register: dump_output

    - name: Print dump output
      debug:
        var: dump_output
