- name: Test MariaDB accessibility
  hosts: controller
  vars_files:
    - roles/test_mariadb/vars/main.yml
  tasks:
    - name: Check if MariaDB is accessible
      community.mysql.mysql_info:
        login_host: "{{ mariadb_host }}"
        login_port: "{{ mariadb_port }}"
        login_user: "{{ mariadb_user }}"
        login_password: "{{ mariadb_password }}"
