- name: Test MariaDB accessibility
  hosts: 10.10.1.11
  vars_files:
    - ../roles/mariadb/vars/mariadb_vars.yaml
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    
    - name: Get container info
      docker_container_info:
        name: mariadb
      register: container_info

    - name: Print container info
      debug:
        var: container_info

    - name: Check if container is running
      debug:
        msg: "Container is running"
      when: container_info.status == 'running'

    - name: Check if MariaDB is accessible
      mysql_info:
        login_host: "{{ mariadb_host }}"
        login_port: "{{ mariadb_port }}"
        login_user: "{{ mariadb_user }}"
        login_password: "{{ mariadb_password }}"
