- name: Prepare MariaDB for the restore process
  hosts: controller
  become: yes
  vars_files:
    - ../globals.yaml
  vars:
    backup_dir: "/tmp/{{ timestamp[0] }}"
  tasks:
    - name: Include tasks for restore process
      include_tasks: ../tasks/prepare_mariadb_restore.yaml
