- name: Prepare MariaDB for the restore process
  hosts: 10.10.1.11
  become: yes
  vars_files:
    - ../globals.yaml
  vars:
    backup_dir: "/tmp/{{ timestamp[0] }}"
  include_tasks: ../tasks/prepare_restore.yaml
